---
sidebar: sidebar
permalink: cleondris_allowing_extra_resources_in_test_failover.html
keywords:
summary:
---

= Allowing Extra Resources in Test Failover
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 0.9 (July 10, 2020)
//
// 2020-07-10 10:54:35.922570
//

[.lead]

Sometimes it is necessary to have more resources in the test failover so that a proper application test can occur. For example, these resources might consist of things like physical anti-spam appliances or load balancers. Or they could include things like databases—which is tricky, because you have to make sure test data does not get into production. I have accomplished this safely several times;  use the following steps as a guideline. (I first allowed extra resources in an IBM AIX environment, but now I have done it in several AIX and HP- UX hosts,  so it is a good outline.) 

. A script executes in the disaster recovery test process (or use a manual process if necessary).

. A separate logical partition (LPAR) is created.

. A virtual network is added to the separate LPAR,  and it is already connected to the test network.

. A script exports and copies the appropriate data to the separate and new LPAR. (It’s likely that you’ll need to have the application on the separate partition,  too. )

. You might need to tweak DNS names or the configuration of the application in the test network to access this new server.

. The test completes successfully.

. After the test is done, and the cleanup occurs, another script runs, and it deletes the separate partition. That step keeps anything from getting into production accidentally.

You can use a similar process to get a domain controller into a test failover:

. Power off the domain controller in the disaster recovery site. Make sure there is another domain controller still running.

. After the domain controller is off,  clone it.

. Power on the original domain controller.

. Put the cloned domain controller on the test network.

. Power on the clone domain controller.

. You should be able to use the domain controller in the test now,  whether for authentication or DNS.  

. When the test is done, delete the cloned domain controller. Don’t skip this step, because you don’t want that domain database talking to the production domain.

It’s best to script these steps and execute the script from the recovery plan. However,  to do that,  you need a script or batch file that can tell whether it is executing in test or real failover—and in real failover,  it does nothing.

